"""Importable FCI academic catalog snapshot for BuddyBot actions.

Generated by tools/export_fci_academic_catalog.py.
Do not edit the generated JSON manually; rerun the exporter after DB updates.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, List, Optional

DATA_PATH = Path(__file__).with_name("fci_academic_catalog_data.json")


def _load() -> dict:
    with DATA_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


_DATA = _load()
DEPARTMENTS: Dict[str, dict] = _DATA["departments"]
COURSES: Dict[str, dict] = _DATA["courses"]


def get_course(code: str) -> Optional[dict]:
    """Return a course dict by exact code (case-insensitive)."""
    return COURSES.get(str(code or "").upper())


def get_department(code: str) -> Optional[dict]:
    """Return a department dict by dept_code (case-insensitive)."""
    return DEPARTMENTS.get(str(code or "").upper())


def find_courses_by_instructor(name: str) -> List[dict]:
    """Return all courses taught by an instructor (partial name match)."""
    query = str(name or "").lower().strip()
    if not query:
        return []
    results = []
    for code, course in COURSES.items():
        if any(query in instructor.lower() for instructor in course.get("instructors", [])):
            results.append({"code": code, **course})
    return sorted(results, key=lambda item: (item["year"], item["semester"], item["code"]))


def find_courses_by_keyword(query: str) -> List[dict]:
    """Search across course code, name, description, and keywords using whole words."""
    q = str(query or "").lower().strip()
    blocked_queries = {
        "it",
        "the",
        "a",
        "an",
        "me",
        "him",
        "her",
        "them",
        "us",
        "that",
        "this",
        "fci",
        "faculty",
    }
    if not q or q in blocked_queries:
        return []
    pattern = re.compile(r"\b" + re.escape(q) + r"\b")
    results = []
    for code, course in COURSES.items():
        searchable = " ".join(
            [
                code,
                course.get("name", ""),
                course.get("description", ""),
                " ".join(course.get("keywords", [])),
            ]
        ).lower()
        if pattern.search(searchable):
            results.append({"code": code, **course})
    return sorted(results, key=lambda item: (item["year"], item["semester"], item["code"]))


def get_courses_by_dept(dept_code: str) -> List[dict]:
    """Return all courses for a department, sorted by year then semester."""
    dept = str(dept_code or "").upper()
    return sorted(
        [{"code": code, **course} for code, course in COURSES.items() if course.get("dept") == dept],
        key=lambda item: (item["year"], item["semester"], item["code"]),
    )


def get_courses_by_year_semester(year: int, semester: int, dept_code: str | None = None) -> List[dict]:
    """Return courses for a year/semester, optionally filtered by department."""
    dept = str(dept_code or "").upper() if dept_code else None
    results = []
    for code, course in COURSES.items():
        if course.get("year") == year and course.get("semester") == semester:
            if dept is None or course.get("dept") == dept:
                results.append({"code": code, **course})
    return sorted(results, key=lambda item: (item["dept"], item["code"]))


def format_course_answer(code: str) -> str:
    """Return a natural-language summary for a course."""
    course = get_course(code)
    if not course:
        return f"I couldn't find a course with code {code}."
    department = DEPARTMENTS.get(course.get("dept"), {"name": course.get("dept", "Unknown")})
    instructors = ", ".join(course.get("instructors") or []) or "TBA"
    return (
        f"**{course['name']}** ({str(code).upper()}) - {course['credit_hours']} credit hours\n"
        f"Department: {department['name']} | Year {course['year']}, Semester {course['semester']}\n"
        f"{course['description']}\n"
        f"Taught by: {instructors}"
    )


def format_instructor_courses_answer(name: str) -> str:
    """Return a natural-language summary of all courses an instructor teaches."""
    courses = find_courses_by_instructor(name)
    if not courses:
        return f"I couldn't find any courses taught by '{name}'."
    lines = [f"Courses taught by {name}:"]
    for course in courses:
        department = DEPARTMENTS.get(course.get("dept"), {"name": course.get("dept", "Unknown")})
        lines.append(
            f"- {course['code']} - {course['name']} "
            f"(Year {course['year']}, Semester {course['semester']}, {department['name']})"
        )
    return "\n".join(lines)
